export * as userService from '~/services/user-service'
export * as roleService from '~/services/role-service'
export * as permissionService from '~/services/permission-service'
export * as rolePermissionService from '~/services/role-permission-service'
export * as userRoleService from '~/services/user-role-service'
