export * as userController from '~/controllers/user-controller'
export * as roleController from '~/controllers/role-controller'
export * as permissionController from '~/controllers/permission-controller'
export * as rolePermissionController from '~/controllers/role-permission-controller'
export * as userRoleController from '~/controllers/user-role-controller'
